TRUNCATE TABLE AMDINS;
TRUNCATE TABLE QUESTIONS;
INSERT INTO admins (email, password) VALUES ('liz@test.com', 'password');
INSERT INTO questions (question, type) VALUES ("You are holding onto your grandmother's hand and the hand of a newborn that you do not know as they hang over the edge of a cliff. You have to let one go to save the other. Who do you let fall to their death? What was your rationale for making the decision?", "dark");
INSERT INTO questions (question, type) VALUES ("Think of the last person who you know that died. You have the chance to give them 1 hour of life back, but you have to give up one year of yours. Do you do it? Why or Why not?", "dark");
INSERT INTO questions (question, type) VALUES ("Your best friend confesses that he/she has feelings for you more than just friendship. He/she is falling in love with you. What do you (or did you) do/say?", "dark");
INSERT INTO questions (question, type) VALUES ("You are walking down the street on your way to work. There is a dog drowning in the canal on the side of the street. Your boss has told you if you are late even once more, you are fired. Do you take the time to save the dogs life? Why or Why not?", "dark");
INSERT INTO questions (question, type) VALUES ("You are at the doctor's office and he has just informed you that you have approximately one month to live. Do you tell anyone/everyone you are going to die? What do you do with your remaining days? Would you be afraid?", "dark");
INSERT INTO questions (question, type) VALUES ("You are on a flight from Honolulu to Chicago non-stop. There is a fire in the back of the plane. You have enough time to make ONE phone call. Who do you call? What do you tell them?", "dark");
INSERT INTO questions (question, type) VALUES ("Would you prefer to know the exact date, time and place of your death or live on without knowing when that moment will come?
What question would you be afraid to tell the truth to?", "dark");
INSERT INTO questions (question, type) VALUES ("If three people uncontrollably were about to commit suicide A pregnant woman, A six-year-old kid, and a 65-year-old woman who would you save and why?", "dark");
INSERT INTO questions (question, type) VALUES ("If sacrificing your own life would save the lives of a specific number of strangers, how many strangers would need to be saved for you to sacrifice your own life? What if the people were friends? How about family?", "dark");
INSERT INTO questions (question, type) VALUES ("If you were going to die at midnight, what would you be doing at 11:45pm?", "dark");
INSERT INTO questions (question, type) VALUES ("What would people say about you at your funeral?", "dark");
INSERT INTO questions (question, type) VALUES ("How would you like to die? Comfortably in bed surrounded by family, doing something you love, or some other way?", "dark");
INSERT INTO questions (question, type) VALUES ("Would you rather be rich and paralyzed from the waist down or poor and able bodied?", "dark");
INSERT INTO questions (question, type) VALUES ("Imagine that a street gang notorious for wearing purple shirts has robbed and murdered several hundred people in your town.  If a man wearing a purple shirt just rang your doorbell, would you answer it? Why or why not?", "dark");
INSERT INTO questions (question, type) VALUES ("Choose one animal species on Earth to utterly eliminate. What are your reasons for this mass extinction?", "dark");
INSERT INTO questions (question, type) VALUES ("If you could steal any one thing in the world and make it yours forever, what would it be?", "dark");
INSERT INTO questions (question, type) VALUES ('What did you have for dinner?', 'light');
INSERT INTO questions (question, type) VALUES ('Where did you grow up?', 'light');
INSERT INTO questions (question, type) VALUES ('Where did you last travel?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your favorite color?', 'light');
INSERT INTO questions (question, type) VALUES ('How many siblings do you have?', 'light');
INSERT INTO questions (question, type) VALUES ('How many cats do you have?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your favorite breed of dog?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your best memory?', 'light');
INSERT INTO questions (question, type) VALUES ('Where did you go to school?', 'light');
INSERT INTO questions (question, type) VALUES ('If you could master one instrument what would it be?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your guilty pleasure?', 'light');
INSERT INTO questions (question, type) VALUES ('Which person from history would you most like to meet?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your favorite film?', 'light');
INSERT INTO questions (question, type) VALUES ('Have you gone out with mismatched socks or shoes on?', 'light');
INSERT INTO questions (question, type) VALUES ('Have you ever seen a ghost or an alien?', 'light');
INSERT INTO questions (question, type) VALUES ('Where would you like to be in five years time?', 'light');
INSERT INTO questions (question, type) VALUES ('Which would you prefer — three wishes over five years or one wish right now?', 'light');
INSERT INTO questions (question, type) VALUES ('When did you last sing to yourself? To someone else?', 'light');
INSERT INTO questions (question, type) VALUES ('If you could have an endless supply of food, what would you get?', 'light');
INSERT INTO questions (question, type) VALUES ('As a child, what did you wish to be when you grew up?', 'light');
INSERT INTO questions (question, type) VALUES ('How do you like to spend a rainy day?', 'light');
INSERT INTO questions (question, type) VALUES ('What will you be like when you are 75?', 'light');
INSERT INTO questions (question, type) VALUES ('You’re writing a message in a bottle. What’s the first line?', 'light');
INSERT INTO questions (question, type) VALUES ('Which celebrity deserves their own monument?', 'light');
INSERT INTO questions (question, type) VALUES ('What did you most hate sharing as a kid?', 'light');
INSERT INTO questions (question, type) VALUES ('What is one of the things on your bucket list?', 'light');
INSERT INTO questions (question, type) VALUES ('What color is your toothbrush?', 'light');
INSERT INTO questions (question, type) VALUES ('Are you a morning or a night person?', 'light');
INSERT INTO questions (question, type) VALUES ('What was the last thing you geeked out about? Where were you?', 'light');
INSERT INTO questions (question, type) VALUES ('If you could be an ambassador, which country would you choose?', 'light');
INSERT INTO questions (question, type) VALUES ('Which mystery would you like the truth about?', 'light');
INSERT INTO questions (question, type) VALUES ('What is the funniest YouTube video you have seen?', 'light');
INSERT INTO questions (question, type) VALUES ('Who is one of your heroes and why do they inspire you?', 'light');
INSERT INTO questions (question, type) VALUES ('What is your favorite amusement park ride?', 'light');
INSERT INTO questions (question, type) VALUES ('What is the scariest movie you have seen?', 'light');
